name: Publish Release Notes to README.io

on:
  release:
    types: [published]
  workflow_dispatch:
    

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to README.io
      run: |
        npm install api --save
        npm install dotenv
        node readmeio_publish.js
      env:
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
